#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=0
set +x
set +v
set +a
umask 077
ENV_FILE=/dev/null
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="${PYTHON:-python3}"
if [[ "${1:-}" == --help ]]; then
  printf '%s\n' '用法：sudo tools/account-wizard.sh [--image 本地应用镜像]' \
    '在 Docker 所在 Linux 服务器运行；Token 与密码仅隐藏输入。' \
    '请先初始化共享入口注册表并部署网关。'
  exit 0
fi
[[ -t 0 && -t 1 ]] || { printf '%s\n' '需要交互式终端，拒绝从管道读取敏感输入。' >&2; exit 1; }
[[ "$EUID" == 0 ]] || { printf '%s\n' '请通过 sudo 在部署服务器运行。' >&2; exit 1; }
trap 'unset CANVAS_TOKEN PASSWORD PASSWORD_AGAIN' EXIT

say '救驾账号管理'
say '1. 新增账号'
say '2. 更新 Canvas Token'
say '3. 重设网页密码'
say '4. 查看账号状态'
ask CHOICE '选择 [1–4]：'
case "$CHOICE" in
  1)
    TOTAL_STAGES=5
    stage '基本信息'
    ask SLUG '账号名称（小写字母、数字、下划线）：'
    ask CANVAS_ORIGIN '学校 Canvas HTTPS 网址（不含路径）：'
    ask TIMEZONE '课程及显示时区（例如 America/Toronto）：'
    say '所有账号使用同一网页登录入口：https://study.qiyi71w.com。'
    stage 'Canvas 凭据'
    say '在学校 Canvas：Account → Settings → Approved Integrations → New Access Token。'
    say '服务器无法代你生成 Token；请在自己电脑的浏览器操作。'
    case "$CANVAS_ORIGIN" in
      https://*) open_url "${CANVAS_ORIGIN%/}/profile/settings" ;;
      *) say 'Canvas 网址必须使用 https://'; exit 1 ;;
    esac
    ask_secret CANVAS_TOKEN '粘贴 Canvas Token（隐藏输入）：'
    stage '网页登录'
    ask USERNAME '网页用户名（3–64 位字母、数字、点、下划线或连字符）：'
    ask_secret PASSWORD '网页密码（12–256 字符，隐藏输入）：'
    ask_secret PASSWORD_AGAIN '再次输入网页密码：'
    [[ "$PASSWORD" == "$PASSWORD_AGAIN" ]] || { say '两次密码不一致，未创建账号。'; exit 1; }
    stage '确认创建'
    "$PYTHON" "$SCRIPT_DIR/cc_admin.py" status
    say '可选：复用已有账号的 AI 供应商配置，不复制其数据或授权。会使用同一供应商账单。'
    ask AI_SOURCE '来源容器完整名称（直接回车跳过）：'
    say "账号：$SLUG；Canvas：$CANVAS_ORIGIN；网页：https://study.qiyi71w.com；用户名：$USERNAME；时区：$TIMEZONE"
    say '默认每日 AI 上限 20；AI 授权关闭。将只读校验 Canvas 身份，再通过共享入口校验登录并启用每日扫描。'
    confirm '确认以上站点属于预期学校，并创建账号？' || { say '已取消，未创建账号。'; exit 0; }
    stage '部署与完成检查'
    printf '%s\0' "$SLUG" "$CANVAS_ORIGIN" "$CANVAS_TOKEN" "$USERNAME" "$PASSWORD" "$TIMEZONE" "$AI_SOURCE" |
      "$PYTHON" "$SCRIPT_DIR/cc_admin.py" create "$@"
    ;;
  2)
    TOTAL_STAGES=2
    stage '选择账号'
    "$PYTHON" "$SCRIPT_DIR/cc_admin.py" status
    ask ACCOUNT '复制完整容器名称：'
    stage '更新 Token'
    say '请在原学校 Canvas 的 Account → Settings 中生成新 Token，必须属于原 Canvas 身份。'
    ask_secret CANVAS_TOKEN '新 Canvas Token（隐藏输入）：'
    confirm '校验身份并短暂重启此账号？' || exit 0
    printf '%s\0' "$ACCOUNT" "$CANVAS_TOKEN" | "$PYTHON" "$SCRIPT_DIR/cc_admin.py" rotate
    ;;
  3)
    TOTAL_STAGES=2
    stage '选择账号'
    "$PYTHON" "$SCRIPT_DIR/cc_admin.py" status
    ask ACCOUNT '复制完整容器名称：'
    stage '重设网页密码'
    ask_secret PASSWORD '新密码（12–256 字符，隐藏输入）：'
    ask_secret PASSWORD_AGAIN '再次输入新密码：'
    [[ "$PASSWORD" == "$PASSWORD_AGAIN" ]] || { say '两次密码不一致，未修改。'; exit 1; }
    confirm '重设密码并撤销这个账号的全部旧会话？' || exit 0
    printf '%s\0' "$ACCOUNT" "$PASSWORD" | "$PYTHON" "$SCRIPT_DIR/cc_admin.py" password
    ;;
  4)
    "$PYTHON" "$SCRIPT_DIR/cc_admin.py" status
    ;;
  *) say '请选择 1、2、3 或 4。'; exit 1 ;;
esac
